# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-14 13:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('type', models.CharField(blank=True, choices=[('starter', 'starter'), ('main', 'main'), ('dessert', 'dessert'), ('side', 'side'), ('drink', 'drink'), ('deal', 'deal')], max_length=8)),
                ('price', models.FloatField(max_length=10)),
                ('dietary_mentions', models.CharField(blank=True, choices=[('vegan', 'vegan'), ('vegetarian', 'vegetarian'), ('halal', 'halal'), ('kosher', 'kosher')], max_length=10)),
                ('allergy_warning', models.CharField(blank=True, choices=[('nuts', 'nuts'), ('milk', 'milk'), ('gluten', 'gluten'), ('glu+mi', 'gluten,milk'), ('glu+nut', 'gluten,nuts'), ('mi+nut', 'milk,nuts'), ('glu+mi+nut', 'milk,nuts,gluten')], max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_range', models.CharField(choices=[('£', '£'), ('££', '££'), ('£££', '£££'), ('££££', '££££')], default='££', max_length=4)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('cuisine', models.CharField(choices=[('indian', 'indian'), ('italian', 'italian'), ('mexican', 'mexican'), ('spanish', 'spanish'), ('chinese', 'chinese'), ('kebab', 'kebab'), ('greek', 'greek'), ('japanese', 'japanese'), ('american', 'american'), ('eclectic', 'eclectic')], default='eclectic', max_length=32)),
                ('address', models.CharField(max_length=8)),
                ('website', models.URLField(blank=True)),
                ('delivery_fee', models.FloatField(blank=True, max_length=8)),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='just_choose.Restaurant'),
        ),
    ]
