# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-15 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('just_choose', '0002_auto_20190314_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='allergy_warning',
            field=models.CharField(blank=True, choices=[('nuts', 'nuts'), ('milk', 'milk'), ('gluten', 'gluten'), ('glu+mi', 'gluten, milk'), ('glu+nut', 'gluten, nuts'), ('mi+nut', 'milk, nuts'), ('glu+mi+nut', 'milk, nuts, gluten'), ('none', 'none')], default='none', max_length=16),
        ),
        migrations.AlterField(
            model_name='menu',
            name='dietary_mentions',
            field=models.CharField(blank=True, choices=[('vegan', 'Vegan'), ('vegetarian', 'Vegetarian'), ('halal', 'Halal'), ('kosher', 'Kosher'), ('none', 'none')], default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='cuisine',
            field=models.CharField(choices=[('indian', 'Indian'), ('italian', 'Italian'), ('mexican', 'Mexican'), ('spanish', 'Spanish'), ('chinese', 'Chinese'), ('kebab', 'Kebab'), ('greek', 'Greek'), ('japanese', 'Japanese'), ('american', 'American'), ('eclectic', 'eclectic')], default='eclectic', max_length=32),
        ),
    ]
